name: climsight
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.10
    - streamlit
    - xarray
    - geopy
    - geopandas
    - pyproj
    - requests
    - requests-mock      
    - pandas
    - folium
    - langchain
    - streamlit-folium
    - netcdf4
    - dask
    - pip
    - matplotlib
    - pip:
        - openai==1.5.0




